import {
  candidateProfileSchema,
  type CandidateClaim,
  type CandidateProfile,
} from "./schemas";

const PROFILE_SOURCE = "User-provided ApplyFlow candidate brief (2026-07-18)";

const claim = (
  id: string,
  category: CandidateClaim["category"],
  field: string,
  value: CandidateClaim["value"],
  status: CandidateClaim["status"] = "verified",
  evidence?: string,
): CandidateClaim => ({
  id,
  category,
  field,
  value,
  status,
  source: PROFILE_SOURCE,
  evidence,
  sensitive: false,
  lastConfirmedAt: "2026-07-18",
});

/**
 * The checked-in seed intentionally contains no address, phone number or email.
 * Runtime contact details are resolved from the named server-side variables.
 */
export const himakarCandidateProfile: CandidateProfile = candidateProfileSchema.parse({
  id: "candidate-himakar-seed",
  preferredName: "Himakar",
  location: {
    city: "Perth",
    state: "Western Australia",
    country: "Australia",
    preferredWorkLocations: [
      "Perth",
      "Western Australia",
      "Remote within Australia",
      "Hybrid in Perth",
    ],
  },
  privateContactReferences: {
    emailEnvVar: "JOB_AGENT_CANDIDATE_EMAIL",
    phoneEnvVar: "JOB_AGENT_CANDIDATE_PHONE",
    addressEnvVar: "JOB_AGENT_CANDIDATE_ADDRESS",
  },
  workRights: {
    visa: "Temporary Graduate visa",
    visaSubclass: "485",
    fullWorkingRights: true,
    australianCitizen: false,
    australianPermanentResident: false,
    securityClearance: null,
    sponsorshipAnswer: null,
    claimIds: [
      "work-rights-visa-type",
      "work-rights-visa-485",
      "work-rights-full",
      "citizenship-no",
      "permanent-residency-no",
      "security-clearance-none",
      "sponsorship-unconfirmed",
    ],
  },
  availability: {
    fullTime: true,
    noticePeriod: null,
    claimIds: ["availability-full-time", "notice-period-unconfirmed"],
  },
  licences: {
    australianDriverLicence: false,
    internationalDriverLicence: null,
    claimIds: ["australian-driver-licence-no", "international-licence-unconfirmed"],
  },
  salaryPreference: {
    currency: "AUD",
    minimum: 90_000,
    maximum: 110_000,
    period: "annual",
    plusSuper: true,
    selectedAmount: null,
    requiresPerOpportunityConfirmation: true,
    claimId: "salary-target-default",
  },
  education: [
    {
      id: "education-uwa-mds",
      qualification: "Master of Data Science",
      institution: "University of Western Australia",
      period: { start: "2023-07", end: "2025-06" },
      details: [
        "Machine Learning",
        "Natural Language Processing",
        "Artificial Intelligence and Adaptive Systems",
        "Bayesian Statistics",
        "Predictive Modelling",
        "Data Warehousing",
        "Business Intelligence",
        "Advanced Algorithms",
        "Distributed Systems",
        "High Performance Computing",
        "Operations Research",
      ],
      claimIds: ["education-uwa-mds-claim"],
    },
    {
      id: "education-lpu-btech",
      qualification: "Bachelor of Technology with Honours in Electronics and Communication Engineering",
      institution: "Lovely Professional University",
      period: { start: "2017-07", end: "2021-06" },
      details: ["GPA: 8.34/10"],
      claimIds: ["education-lpu-btech-claim", "metric-btech-gpa"],
    },
  ],
  employment: [
    {
      id: "employment-ritz-carlton",
      employer: "The Ritz-Carlton Perth",
      role: "Banquet and Events Food and Beverage",
      period: { start: "2023-11", end: null },
      current: true,
      highlights: [
        "Supported banquet and event operations, guest service, logistics and operational setup",
        "Collaborated with frontline staff and hotel leadership",
        "Identified operational problems and introduced a digital beverage-audit solution",
        "Built credibility with staff, supervisors, managers and directors",
      ],
      claimIds: ["employment-ritz-carlton-claim"],
    },
    {
      id: "employment-norwood",
      employer: "Norwood Systems",
      role: "Data Science / AI Capstone and Internship",
      period: { start: "2024-07", end: "2025-02" },
      current: false,
      highlights: [
        "Worked on real-time speech-to-text and text-to-speech systems",
        "Built iOS and Flutter clients for speech-agent workflows",
        "Used Whisper and VoxLingua language identification",
        "Used WebSocket endpoints, streaming audio and silence-based segmentation",
      ],
      claimIds: ["employment-norwood-claim"],
    },
    {
      id: "employment-kids-health",
      employer: "Kids Health / NursePrac",
      role: "Data Analysis Intern",
      period: { start: "2025-02", end: "2025-05" },
      current: false,
      highlights: [
        "Automated data reporting and dashboard workflows",
        "Produced summaries and insights",
        "Reduced manual reporting work",
        "Supported practical healthcare-related analytics",
      ],
      claimIds: ["employment-kids-health-claim"],
    },
    {
      id: "employment-hungry-jacks",
      employer: "Hungry Jack's",
      role: "Assistant Supervisor",
      period: { start: "2023-08", end: "2023-12" },
      current: false,
      highlights: [
        "Customer service and team coordination",
        "Operational supervision and working under pressure",
      ],
      claimIds: ["employment-hungry-jacks-claim"],
    },
    {
      id: "employment-cognizant",
      employer: "Cognizant",
      role: "Programmer Analyst Trainee",
      period: { start: "2021-03", end: "2021-09" },
      current: false,
      highlights: [
        "Completed software-development training",
        "Worked with the Spring framework, database management systems and enterprise development practices",
      ],
      claimIds: ["employment-cognizant-claim"],
    },
  ],
  projects: [
    {
      id: "project-liquid-audit",
      name: "The Liquid Audit",
      type: "SaaS beverage-audit and stock-control platform",
      organisation: "Omnari",
      status: "Used in a live five-star hotel environment",
      highlights: [
        "Identified an operational business problem and designed and built a working software solution",
        "Worked across frontend, backend, APIs, database and deployment",
        "Tested with real hotel users and iterated from operational feedback",
        "Communicated with staff and management",
        "Supported live use for approximately nine months by July 2026",
      ],
      technologies: ["TypeScript", "React", "Node.js", "REST APIs", "Database design"],
      claimIds: ["project-liquid-audit-claim", "metric-liquid-audit-live-use"],
    },
    {
      id: "project-speech-agent",
      name: "Speech-to-speech meeting agent",
      type: "Applied AI",
      highlights: [
        "Implemented real-time speech recognition, synthesis and language identification",
        "Worked with audio streaming and silence-based speech segmentation",
      ],
      technologies: [
        "Whisper",
        "VoxLingua",
        "WebSockets",
        "Swift",
        "Flutter",
        "Audio streaming",
      ],
      claimIds: ["project-speech-agent-claim"],
    },
    {
      id: "project-fast-home-repair",
      name: "FastHomeRepair",
      type: "Cloud software project",
      highlights: ["Built with Azure application and AI services"],
      technologies: [
        "Azure Functions",
        "Node.js",
        "React",
        "Cosmos DB",
        "Blob Storage",
        "Azure Computer Vision",
        "Azure AI services",
        "Azure Search",
      ],
      claimIds: ["project-fast-home-repair-claim"],
    },
  ],
  skills: [
    "Python",
    "JavaScript",
    "TypeScript",
    "Node.js",
    "React",
    "SQL",
    "Flutter",
    "Swift",
    "Azure",
    "REST APIs",
    "WebSockets",
    "Data analysis",
    "Machine learning",
    "Natural language processing",
    "Generative AI",
    "Automation",
    "Dashboard development",
    "Database design",
    "Applied AI",
    "Product prototyping",
    "Stakeholder communication",
    "Operational problem-solving",
    "Technical documentation",
  ],
  preferredRoles: [
    "Applied AI Engineer",
    "AI Engineer",
    "AI Automation Engineer",
    "AI Solutions Engineer",
    "Forward Deployed AI Engineer",
    "Forward Deployed AI Scientist",
    "Junior Machine Learning Engineer",
    "Graduate Machine Learning Engineer",
    "Data Scientist",
    "Graduate Data Scientist",
    "Junior Data Scientist",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Product Data Analyst",
    "Analytics Engineer",
    "Software Engineer",
    "Full-Stack Developer",
    "Backend Developer",
    "AI or data Solutions Consultant",
    "Technical Business Analyst with automation responsibilities",
    "AI, data or SaaS Implementation Consultant",
    "Graduate technology program",
  ],
  excludedRequirements: [
    "Australian citizenship required",
    "Australian permanent residency required",
    "Defence or Baseline security clearance required",
    "NV1 or NV2 clearance required",
    "Australian driver licence required",
    "Unpaid or commission-only work",
  ],
  claims: [
    claim("preferred-name", "personal", "preferredName", "Himakar"),
    claim("location-perth", "location", "location", "Perth, Western Australia"),
    claim("work-rights-visa-type", "work-rights", "visa", "Temporary Graduate visa"),
    claim("work-rights-visa-485", "work-rights", "visaSubclass", "485"),
    claim("work-rights-full", "work-rights", "fullWorkingRights", true),
    claim("citizenship-no", "work-rights", "australianCitizen", false),
    claim("permanent-residency-no", "work-rights", "australianPermanentResident", false),
    claim("security-clearance-none", "work-rights", "securityClearance", "None"),
    claim(
      "sponsorship-unconfirmed",
      "application-answer",
      "requiresSponsorship",
      "Not provided",
      "needs-confirmation",
    ),
    claim("availability-full-time", "availability", "fullTime", true),
    claim(
      "notice-period-unconfirmed",
      "availability",
      "noticePeriod",
      "Not provided",
      "needs-confirmation",
    ),
    claim("australian-driver-licence-no", "licence", "australianDriverLicence", false),
    claim(
      "international-licence-unconfirmed",
      "licence",
      "internationalDriverLicence",
      "Not confirmed",
      "needs-confirmation",
    ),
    claim(
      "salary-target-default",
      "salary",
      "graduateJuniorTarget",
      "AUD 90,000-110,000 plus super",
      "user-entered",
    ),
    claim("education-uwa-mds-claim", "education", "uwaMasterDataScience", "Master of Data Science, University of Western Australia, July 2023-June 2025"),
    claim("education-lpu-btech-claim", "education", "lpuBTech", "Bachelor of Technology with Honours in Electronics and Communication Engineering, July 2017-June 2021"),
    claim("metric-btech-gpa", "metric", "btechGpa", "8.34/10"),
    claim("employment-ritz-carlton-claim", "employment", "ritzCarlton", "Banquet and Events Food and Beverage, November 2023-present"),
    claim("employment-norwood-claim", "employment", "norwood", "Data Science / AI Capstone and Internship, July 2024-February 2025"),
    claim("employment-kids-health-claim", "employment", "kidsHealth", "Data Analysis Intern, February 2025-May 2025"),
    claim("employment-hungry-jacks-claim", "employment", "hungryJacks", "Assistant Supervisor, August 2023-December 2023"),
    claim("employment-cognizant-claim", "employment", "cognizant", "Programmer Analyst Trainee, March 2021-September 2021"),
    claim("project-liquid-audit-claim", "project", "liquidAudit", "SaaS beverage-audit and stock-control platform used in a live five-star hotel environment"),
    claim("metric-liquid-audit-live-use", "metric", "liquidAuditLiveUse", "approximately nine months by July 2026"),
    claim(
      "metric-business-results-prohibited",
      "metric",
      "unprovidedBusinessMetrics",
      "Revenue, savings, customer counts, client counts and contract values were not provided",
      "prohibited-from-inference",
    ),
    claim(
      "salary-150k-prohibited",
      "salary",
      "automaticSalary150000",
      "AUD 150,000 must not be used without per-opportunity selection",
      "prohibited-from-inference",
    ),
    claim("project-speech-agent-claim", "project", "speechAgent", "Speech-to-speech meeting agent using Whisper, VoxLingua, WebSockets, Swift and Flutter"),
    claim("project-fast-home-repair-claim", "project", "fastHomeRepair", "FastHomeRepair using Azure Functions, Node.js, React, Cosmos DB, Blob Storage, Azure Computer Vision, Azure AI services and Azure Search"),
    claim("skills-verified", "skill", "coreSkills", [
      "Python", "JavaScript", "TypeScript", "Node.js", "React", "SQL", "Flutter", "Swift", "Azure", "REST APIs", "WebSockets", "Data analysis", "Machine learning", "Natural language processing", "Generative AI", "Automation", "Dashboard development", "Database design", "Applied AI", "Product prototyping", "Stakeholder communication", "Operational problem-solving", "Technical documentation",
    ]),
  ],
  updatedAt: "2026-07-18",
});

export function getCandidateClaim(
  profile: CandidateProfile,
  claimId: string,
): CandidateClaim | undefined {
  return profile.claims.find((candidateClaim) => candidateClaim.id === claimId);
}

export function isClaimUsableAsEvidence(candidateClaim: CandidateClaim): boolean {
  return candidateClaim.status === "verified" || candidateClaim.status === "user-entered";
}

export function getCandidateEvidence(profile: CandidateProfile): CandidateClaim[] {
  return profile.claims.filter(isClaimUsableAsEvidence);
}

export function calculateProfileCompleteness(profile: CandidateProfile): number {
  const requiredClaimIds = [
    "preferred-name",
    "location-perth",
    "work-rights-visa-type",
    "work-rights-visa-485",
    "work-rights-full",
    "citizenship-no",
    "permanent-residency-no",
    "availability-full-time",
    "australian-driver-licence-no",
    "education-uwa-mds-claim",
    "employment-norwood-claim",
    "skills-verified",
  ];
  const usableIds = new Set(getCandidateEvidence(profile).map((item) => item.id));
  const present = requiredClaimIds.filter((claimId) => usableIds.has(claimId)).length;
  return Math.round((present / requiredClaimIds.length) * 100);
}
